# Generated by Django 4.1.5 on 2023-01-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datamhs',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('ipk', models.FloatField(max_length=18.2)),
                ('penghasilan', models.IntegerField()),
                ('sertifikat', models.IntegerField()),
                ('tanggungan', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kriteria',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('C1', models.FloatField(max_length=18.2)),
                ('C2', models.FloatField(max_length=18.2)),
                ('C3', models.FloatField(max_length=18.2)),
                ('C4', models.FloatField(max_length=18.2)),
                ('C5', models.FloatField(max_length=18.2)),
            ],
        ),
        migrations.CreateModel(
            name='normalisasi',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('W1', models.FloatField(max_length=18.2)),
                ('W2', models.FloatField(max_length=18.2)),
                ('W3', models.FloatField(max_length=18.2)),
                ('W4', models.FloatField(max_length=18.2)),
                ('W5', models.FloatField(max_length=18.2)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('maxresult', models.FloatField(max_length=4.2)),
            ],
        ),
    ]
